project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"

website:
  title: "Quarto POC"
  favicon: img/favicon.ico
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true

  navbar:
    logo: img/favicon.ico
    logo-alt: Bioinformatics.ca Logo
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Introduction
        href: intro/course-schedule.qmd
      - text: Content
        href: content/day-1.qmd
  
  sidebar:
    - title: "Introduction"
      style: "docked"
      background: light
      contents:
        - intro/course-schedule.qmd
        - intro/gen-form.qmd

    - title: "Content"
      contents:
        - content/day-1.qmd
        - content/day-2.qmd


  page-footer:
    left: "Copyright 2024, CBW DEV?" 
    right:
      - icon: youtube
        href: https://www.youtube.com/@bioinformaticsdotca
      - icon: github
        menu:
            - text: Source Code
              href:  https://github.com/cbw-dev/
            - text: Report a Bug
              href:  https://github.com/cbw-dev/

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true